version = 0.1

[default.deploy.parameters]
stack_name = "tweeter-server"
resolve_s3 = true
s3_prefix = "tweeter-server"
region = "us-east-1"
profile = "tweeter-dev"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"

[ci.deploy.parameters]
stack_name = "tweeter-server"
resolve_s3 = true
s3_prefix = "tweeter-server"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []

[ci.global.parameters]
region = "us-east-1"
